### PR TITLE
refactor: use setAllMethodNames method

### PR DESCRIPTION
**Pull request by peixotoleonardo**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

ScheduleExplorer is using  scanFromPrototype of the MetadataScanner, this method is deprecated.

Issue Number: N/A

## What is the new behavior?

I used the method getAllMethodNames for doing the same thing of the scanFromPrototype method

## Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by micalevisk** [comment]
as that `getAllMethodNames` method was added in `@nestjs/common` v9.3.3, I'd say that this is a breaking change for `@nestjs/schedule@3` because it would no longer support old versions of `@nestjs/common`

https://github.com/nestjs/schedule/blob/d65d1a06c899a3578d9635afabd44919efeaca22/package.json#L52-L54

**Comment by sheerlox** [comment]
> as that `getAllMethodNames` method was added in `@nestjs/common` v9.3.3, I'd say that this is a breaking change for `@nestjs/schedule@3` because it would no longer support old versions of `@nestjs/common`
> 
> https://github.com/nestjs/schedule/blob/d65d1a06c899a3578d9635afabd44919efeaca22/package.json#L52-L54

stepping in to mention that if there's a breaking change to be released, it might be interesting to bundle it with https://github.com/nestjs/schedule/pull/1432 and the PR I need to make accordingly. I'll be following the topic.

**Comment by peixotoleonardo** [comment]
> as that `getAllMethodNames` method was added in `@nestjs/common` v9.3.3, I'd say that this is a breaking change for `@nestjs/schedule@3` because it would no longer support old versions of `@nestjs/common`
> 
> https://github.com/nestjs/schedule/blob/d65d1a06c899a3578d9635afabd44919efeaca22/package.json#L52-L54

I could check if the method `getAllMethodNames` exists; if it does not exist, I will use the old method.

**Comment by micalevisk** [comment]
> I could check if the method getAllMethodNames exists; if it does not exist, I will use the old method.

sounds good. Also, add a `// TODO(v4): remove this after dropping support for nestjs v9.3.2` somewhere

**Comment by peixotoleonardo** [comment]
I will close this PR because I didn't create a branch to make the changes

**Pull request closed without merging**
