### PR TITLE
chore(deps): remove dev dependency @types/cron

### PR DESCRIPTION
**Pull request by sheerlox**
Since @renovate-bot force-pushed `renovate/cron-2.x` (https://github.com/nestjs/schedule/pull/1355) after https://github.com/nestjs/schedule/pull/1356 had been merged into it, the changes were lost and did not reach the `master` branch. This PR reintroduces these changes.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] ~Tests for the changes have been added (for bug fixes / features)~
- [ ] ~Docs have been added / updated (for bug fixes / features)~

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [X] Other... Please describe: `Development dependencies & documentation update`

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## Other information

Reproduces PR: https://github.com/nestjs/schedule/pull/1356

Commands ran (successfully) to test the changes:
```bash
$ npm run build
$ npm run test:integration
```

### CODE REVIEW

**Review by Tony133 — APPROVED** [review]

**Comment by Tony133** [comment]
@sheerlox as soon as you find some time, can you resolve the conflicts of this PR?

**Comment by sheerlox** [comment]
@Tony133 done 😉

**Comment by Tony133** [comment]
thank you very much @sheerlox  😉👍

**Comment by Tony133** [comment]
@kamilmysliwiec  as soon as you find some time can you merge this?

**Review by Tony133 — APPROVED** [review]

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
