### PR TITLE
feat(schedule) allow safe delete cronjob/interval/timeout for name not exist

### PR DESCRIPTION
**Pull request by zieglar**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
allow safe delete schedule job for job name not exist

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by kamilmysliwiec** [comment]
Can you elaborate more on this PR? What exactly it improves? What errors did you notice?

**Comment by zieglar** [comment]
When I use @nestjs/schedule for schedule job, I need repeat code for check job exist and safe delete job, it not useful, so I submit this PR for skip Error `No ${schedulerName} was found with the given name (${name}). Check that you created one with a decorator or with the create API.`

**Comment by kamilmysliwiec** [comment]
So instead of wrapping the entire logic in `if` conditions, I would say we should add a few new methods, respectively: `hasTimeout()`, `hasInterval()`, and `hasCronJob()` that return boolean indicating whether a timeout/interval/cron with a given name exists in the registry.

**Comment by zieglar** [comment]
you mean like this ?
```
  hasInterval(name: string) {
    return this.getIntervals().includes(name);
  }
  deleteInterval(name: string) {
    if (this.hasInterval(name)) {
      const interval = this.getInterval(name);
      clearInterval(interval);
      this.intervals.delete(name);
    }
  }
```

**Comment by kamilmysliwiec** [comment]
`hasX` methods shouldn't be hardcoded inside `deleteX` methods. This should be a developer responsibility.

**Comment by zieglar** [comment]
I don't think it's friendly enough to direct throw the NO_SCHEDULER_FOUND error, the code for a planned task isn't always in an obvious place to trigger it, and it's easy to introduce deviations in execution when the documentation is inadequate, and then the system can't continue to execute with an error.

**Comment by kamilmysliwiec** [comment]
We don't plan to hardcode these checks (ifs) in `getX` methods. Would you like to add `hasX` methods as part of this PR?

**Comment by zieglar** [comment]
> We don't plan to hardcode these checks (ifs) in `getX` methods. Would you like to add `hasX` methods as part of this PR?

added

**Comment by kamilmysliwiec** [comment]
`deleteX` methods are still being used in `getX` methods

**Comment by zieglar** [comment]
I'm not sure what you mean and what you're ultimately trying to achieve.

**Comment by kamilmysliwiec** [comment]
`deleteX` methods shouldn't be used within `getX` methods. We should leave this responsibility to the developer instead of introducing side-effects

**Pull request closed without merging**
